use_frameworks!

platform :ios, '11.0'

target 'JBUniMP_Example' do
  pod 'JBangUniMP', :path => '../'

  target 'JBUniMP_Tests' do
    inherit! :search_paths

  end
end

# M1 系列 Mac 模擬器運行需要添加以下配置
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
        end
    end
end
